version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py
formats:
  - htmlzip  # 可选：生成离线包

subprojects:
  zh-cn:
    name: "zh"  # 匹配 locales/ 中的目录名
    language: "zh_CN"
  en:
    name: "en"
    language: "en"